pipeline {
    agent any

    environment {
        PYTHON = 'python3'
        VENV = '.venv'
    }

    stages {
        stage('Checkout') {
            steps {
                echo 'Cloning repository from GitHub...'
                git branch: 'main', credentialsId: 'kevin-0703', url: 'https://github.com/kevin-0703/alx-backend-python.git'
            }
        }

        stage('Install dependencies') {
            steps {
                echo 'Setting up Python environment and installing dependencies...'
                sh '''
                ${PYTHON} -m venv ${VENV}
                source ${VENV}/bin/activate
                pip3 install --upgrade pip
                pip3 install -r messaging_app/requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                echo 'Running tests with pytest...'
                sh '''
                source ${VENV}/bin/activate
                pytest messaging_app/tests --junitxml=report.xml
                '''
            }
            post {
                always {
                    junit 'report.xml'
                }
            }
        }
    }

    post {
        always {
            echo 'Pipeline completed successfully.'
        }
    }
}
