# Generated by Django 5.2.4 on 2025-09-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0002_rename_password_hash_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=128),
        ),
    ]
