apiVersion: v1
kind: Service
metadata:
  name: messaging-app-service
spec:
  selector:
    app: messaging
    version: blue # Switch to green later
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
