# Generated by Django 5.2.4 on 2025-09-20 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="password_hash",
            new_name="phone_number",
        ),
    ]
